n_samples: [50, 50, 50]
node_feature_sets:
    [
        ["feature1", "feature2", "feature3", "feature4", "feature5"],
        ["feature1", "feature2", "feature3", "feature4", "feature5"],
        ["feature1", "feature2", "feature3", "feature4", "feature5"],

    ]
data_seed: 43
impute: False
nan_ratio: [0.1, 0.1, 0.1]
output_type: "continuous"
