model_type: ["modn"]
seed: [45,]

# Hyperparameters
state_dim: [14]
learning_rate: [0.001]
local_epochs: [1]  # Number of epochs to train locally on each node
federated_rounds: [100]  # Number of federated learning rounds
filename: ["tmp.csv"]
feature_decoding: [False]
batch_size : [30]
shuffle: [True]
predict_all: [True]
weight: [True]

hidden_layers_enc_shared: [[16, 16,]]
hidden_layers_enc_private: [[16]] 
hidden_layers_dec_shared: [[16, 16, ]]
hidden_layers_dec_private: [[16]]
hidden_layers_decoding: [[]]